name: Testing

on:
  push:
    branches: [main]
  pull_request:
    
jobs:
  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Install cmake
        run: |
          sudo apt-get install cmake
          sudo apt-get install ninja-build
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install pytest
        run: |
          pip install pytest
      - name: test
        run: |
          make test
